# Generated by Django 3.2.5 on 2021-07-30 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertypes',
            options={'verbose_name_plural': 'User Types'},
        ),
    ]
