# Generated by Django 3.2.5 on 2021-08-01 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20210801_1835'),
        ('profiles', '0003_auto_20210801_1339'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
