# Generated by Django 3.2.5 on 2021-08-07 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20210806_2155'),
        ('profiles', '0007_auto_20210807_0812'),
    ]

    operations = [
    ]
