# Generated by Django 3.2.5 on 2021-07-30 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobsteps_jobtimes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobsteps',
            options={'verbose_name_plural': 'Job Steps'},
        ),
        migrations.AlterModelOptions(
            name='jobtimes',
            options={'verbose_name_plural': 'Job Times'},
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.jobstatus'),
        ),
    ]
