# Generated by Django 3.2.5 on 2021-08-08 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('jobs', '0009_job_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.assets'),
        ),
    ]
