# Generated by Django 3.2.5 on 2021-08-08 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_remove_ppm_type'),
        ('jobs', '0010_job_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='ppm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.ppm'),
        ),
    ]
