# Generated by Django 3.2.5 on 2021-08-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_job_ppm'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
