# Generated by Django 3.2.5 on 2021-08-07 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AlterModelOptions(
            name='projectstatus',
            options={'verbose_name_plural': 'Project Statuses'},
        ),
    ]
