# Generated by Django 3.2.5 on 2022-01-29 11:05

from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.ForeignKey(default=projects.models.get_default_status, on_delete=django.db.models.deletion.CASCADE, to='projects.projectstatus'),
        ),
    ]
