# Generated by Django 3.2.5 on 2021-08-07 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0009_job_project'),
        ('ancillaries', '0003_suppliers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=40)),
                ('installation_date', models.DateField()),
                ('description', models.TextField()),
                ('barcode', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Assets',
            },
        ),
        migrations.CreateModel(
            name='AssetTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Asset Types',
            },
        ),
        migrations.CreateModel(
            name='PPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_interval', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.assets')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
            options={
                'verbose_name_plural': 'PPMs',
            },
        ),
        migrations.AddField(
            model_name='assets',
            name='asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.assettypes'),
        ),
        migrations.AddField(
            model_name='assets',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ancillaries.departments'),
        ),
        migrations.AddField(
            model_name='assets',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ancillaries.locations'),
        ),
        migrations.AddField(
            model_name='assets',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ancillaries.suppliers'),
        ),
    ]
