# Generated by Django 3.2.5 on 2021-08-08 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_status'),
        ('jobs', '0010_job_asset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ancillaries', '0003_suppliers'),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ppm',
            name='job',
        ),
        migrations.AddField(
            model_name='ppm',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ppm',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppm',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ancillaries.departments'),
        ),
        migrations.AddField(
            model_name='ppm',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ppm',
            name='job_title',
            field=models.CharField(default='Test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppm',
            name='priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.jobpriority'),
        ),
        migrations.AddField(
            model_name='ppm',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project'),
        ),
        migrations.AddField(
            model_name='ppm',
            name='status',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.jobstatus'),
        ),
        migrations.AddField(
            model_name='ppm',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.jobtypes'),
        ),
        migrations.AlterField(
            model_name='ppm',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.assets'),
        ),
    ]
