# Generated by Django 3.2.5 on 2021-08-08 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_job_asset'),
        ('assets', '0002_auto_20210808_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ppm',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='ppm',
            name='project',
        ),
        migrations.RemoveField(
            model_name='ppm',
            name='status',
        ),
        migrations.AlterField(
            model_name='ppm',
            name='asset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assets.assets'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ppm',
            name='type',
            field=models.ForeignKey(default=4, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.jobtypes'),
        ),
    ]
