# Generated by Django 3.2.5 on 2021-08-08 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20210808_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ppm',
            name='type',
        ),
    ]
