# Generated by Django 3.2.4 on 2021-07-25 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ancillaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departments',
            options={'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='locations',
            options={'verbose_name_plural': 'Locations'},
        ),
    ]
