# Generated by Django 3.2.5 on 2021-08-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ancillaries', '0002_auto_20210725_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Suppliers',
            },
        ),
    ]
