# Generated by Django 3.2.5 on 2021-08-13 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_job_due_date'),
        ('stocks', '0002_auto_20210809_1743'),
        ('notifications', '0002_remove_notification_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='value',
        ),
        migrations.AddField(
            model_name='notification',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.job'),
        ),
        migrations.AddField(
            model_name='notification',
            name='stock_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.stockitem'),
        ),
    ]
